### PR TITLE
Some function simplificatons & future-proofing

### PR DESCRIPTION
**Pull request by 10xJSChad**

### CODE REVIEW

**Comment by 10xJSChad** [comment]
Whoops, hit enter before I could document my changes.
I renamed the greyLevel function to isGrayLevel to be clearer, and to keep consistent with the use of 'gray' instead of 'grey'.
Created new clearSlot and getFirstEmptySpace functions.
Future-proofed deleteItem by allowing use with any bag/container.

**Comment by 10xJSChad** [comment]
Smaller, less significant changes have been made as well.
I'd suggest making use of the Issues and Projects features on GitHub for more transparency on future features and what you're currently working on (by assigning an issue to yourself).

Taking advantage of Issues would make it a lot easier for myself and other potential contributors to find a feature to work on and not accidentally start making something that another person is already working on.

**Comment by Flotib** [comment]
Hey! Thank you again for your contribution, your changes are great.
You commented the "emptySpace(target)" function and asked if it will be used in futur. I already use it to show the free space on the bag button like in wow. So even if the bag is closed you know if you're full or not. I don't think this function will be used somewhere else. We'll see.

I don't really know how to use Issues and Projects features on Github but I'll check that because I think that's a good idea.

**Comment by 10xJSChad** [comment]
Ah I totally forgot that the emptySpace function is used in index.html, thanks

**Pull request merged**
